PR For Private-Event project review
umairarshadbutt/Private-Events pull request #1
Opened 2020-10-01 17:38 UTC by umairarshadbutt

The purpose of PR is to evaluate the practice project (Private Event).
This project is developed for a good understanding of Active record Association

2020-10-02 00:37 UTC, christianotieno requested changes
# Changes Required ♻️ 
Hello team. 👋 
The word done is really solid. Keep it up. 👏 
Before we merge this, let's work on the highlighted issues below 👇 thank you.

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-10-02 00:37 UTC, christianotieno commented on README.md
> +
## Add a screenshot of your page on the README 

- [ ] Add a screenshot of your page here. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

2020-10-02 00:37 UTC, christianotieno commented on README.md
> +- Run `rails server`
## Add test instructions
- [ ] Once implemented, be sure to also add instructions to run the tests as well. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

2020-10-02 00:37 UTC, christianotieno commented on app/views/events/index.html.erb
> +    <% end %>
## Remove all the logic related code 

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* Check this article on [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code) and [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more info about this. Thank you. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-02 00:37 UTC, christianotieno commented on app/views/events/index.html.erb
> +      <% end %>
## Remove all the logic related code 

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* Check this article on [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code) and [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more info about this. Thank you. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-02 00:37 UTC, christianotieno commented on app/views/events/index.html.erb
> +      <% end %>
## Remove all the logic related code 

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* Check this article on [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code) and [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more info about this. Thank you. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-02 00:37 UTC, christianotieno commented on app/views/events/show.html.erb
> +  </ul>
## Remove all the logic related code 

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* Check this article on [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code) and [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more info about this. Thank you. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-02 00:37 UTC, christianotieno commented on app/views/events/show.html.erb
> +<% end %>
## Remove all the logic related code 

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* Check this article on [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code) and [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) for more info about this. Thank you. [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright.

2020-10-02 00:37 UTC, christianotieno commented on test/application_system_test_case.rb
> +require 'test_helper'
#### Tests

* [ ] Make sure models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] Make sure authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] Make sure event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

2020-10-02 16:42 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Good job so far :+1: However, before this project can be approved you need to consider the required changes outlined in the previous review.

- **_Remove all the logic from the views, use helpers instead_**

- **_Fix the tests; it output errors when I ran the tests._**

#### _Reviewed by Temitayo Adeleke._

2020-10-03 01:16 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Let's work on all requirements as requested by previous TSE's. 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-03 01:20 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
Let's work on all requirements as requested by previous TSE's. 
- [ ] The test suite is still failing 
- [ ] There should be NO application logic in the views nor helpers
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-03 20:43 UTC, umairarshadbutt commented
I'm using a loop for displaying events in views. I think we can use the loop in reviews.

2020-10-03 21:23 UTC, kubilaycaglayan requested changes
Hello Team :wave: 
Status: Changes Required :recycle: 

Thank you very much for all your effort! 
I want to point out 2 things, let's talk about them ⏬

### No Logic in The Views

- [x]  There should be absolutely NO logic in views.

Just like you are doing it very well by creating partials, you should create the logics in the helpers to separate and organize the code 🙏

:bulb: Please check the inline comments below, I tried to point out some of the `if` statements that I saw in the views. Please move all of them as functional methods to the helpers. 

:point_right: You can use this source to learn how: https://www.rubyguides.com/2020/01/rails-helpers/
Also:
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### Tests 
There are two things about tests:

- [ ]  You have a folder named `test`. I believe this is coming from the rails template. And it is distorting the `rspec` command. Please delete it if you are not using it. I had to delete it to run the instructions in the readme file in a healthy way.

- [ ]  One test case is failing on my side. I will share a screenshot to give you more insight into it.
**Screenshot from test results :camera_flash:**
![image](https://user-images.githubusercontent.com/60448833/95001875-11392f80-05d7-11eb-91d1-ccbd6b4ae22d.png)

### That's it, team! After making these changes, please request another code review :angel: :blush: 

With all my respect :pray:

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/users/_show.html.erb
> +  <h3 class="text-center">User profile page for: <%= @user.full_name if @user %></h3>
:bulb: This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/users/_show.html.erb
> +  <h3 class="text-center">User profile page for: <%= @user.full_name if @user %></h3>
Both ifs.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/users/_new.html.erb
> +  <nav class="navbar navbar-expand-lg navbar-light bg-light">
:bulb:  This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/sessions/new.html.erb
> +<% if current_user == nil && !current_user? %>
:bulb:  This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/sessions/welcome.html.erb
> +<% if current_user == nil && !current_user? %>
:bulb:  This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/events/_show.html.erb
> +<% if current_user? %>
:bulb: This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/events/_new.html.erb
> +<% if current_user? %>
:bulb: This is a "logic in the views" situation.

2020-10-03 21:23 UTC, kubilaycaglayan commented on app/views/events/_index.html.erb
> +<% if current_user? %>
:bulb: This is a "logic in the views" situation.

2020-10-04 20:11 UTC, umairarshadbutt commented
- Move these views logic into helper with the help of [StackOverflow Solution](https://stackoverflow.com/questions/34597553/how-should-i-remove-this-logic-from-my-view-in-rails)
- Remove this one test case  :camera_flash:

![image](https://user-images.githubusercontent.com/60448833/95001875-11392f80-05d7-11eb-91d1-ccbd6b4ae22d.png)

2020-10-04 21:45 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team!👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

-  As was pointed out to you in previous reviews, there should be no logic in the views. Take a look at my comments for instances where the logic needs to be removed. 

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/events/_index.html.erb
> +      <% end %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/events/_index.html.erb
> +      </tbody>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/events/_index.html.erb
> +        <% end %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/events/_show.html.erb
> +
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/sessions/welcome.html.erb
> +  <% if current_user %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/users/_show.html.erb
> +            <% end %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/users/_show.html.erb
> +            <% end %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-04 21:45 UTC, BrittanyBlake commented on app/views/users/_show.html.erb
> +            <% end %>
- [ ] There should be no logic in the views. Please encapsulate all of the view-related logic in your view helpers: **(app/helpers/*_helper.rb)**

2020-10-05 11:46 UTC, umairarshadbutt commented
I moved the logic from views to helpers. Now there are loops in views

2020-10-05 14:16 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello  Umair Arshad** 
Great job following the improvements of the last review :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [ ] user show route should also show the past and upcoming attendees from the user.
- [ ] Add unit tests for methods that retrieve past and upcoming events and attendees.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-10-05 18:11 UTC, umairarshadbutt commented
Hi
I'm sharing my system the user route screenshot
![user_events](https://user-images.githubusercontent.com/29689273/95116184-14abf280-0760-11eb-9e72-5f84c1d24539.png)

2020-10-05 18:24 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello @umairarshadbutt :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-05 19:11 UTC, merged